key_bindings:
  # Ctrl+E: Move cursor to the end of the line
  - { key: E, modifiers: Control, action: "MoveToLineEnd" }
  
  # Ctrl+A: Move cursor to the beginning of the line
  - { key: A, modifiers: Control, action: "MoveToLineStart" }
